In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
#readint the file
df=pd.read_csv("digital_burnout.csv")
df.head() #first 5 rows

,user_id,age,occupation,work_mode,device_usage_type,daily_screen_time,social_media_hours,doomscrolling_duration,app_switch_frequency,notification_count,...,internet_stability,remote_work_days,motivation_level,mental_fatigue,emotional_exhaustion,work_satisfaction,mental_state,burnout_risk,productivity_score,productivity_category
0,1,56,Content Creator,Office,Entertainment-Centric,8.8,5.0,1.2,41,112,...,3,4,8.0,10,4,8,Balanced,46,100,High
1,2,46,Student,Hybrid,Work-Centric,10.3,2.2,2.4,119,168,...,7,6,5.0,7,9,7,Balanced,57,96,High
2,3,32,Software Engineer,Remote,Balanced,6.5,4.6,1.0,121,199,...,9,6,8.0,5,2,6,Balanced,29,79,High
3,4,25,Designer,Office,Balanced,9.6,1.2,0.1,85,122,...,10,5,6.0,4,5,3,Burnout,57,63,Medium
4,5,38,Analyst,Hybrid,Work-Centric,13.3,1.6,1.9,221,73,...,1,1,4.0,7,9,7,Focused,64,89,High

In [3]:
df.columns,len(df.columns) #comlumn details

(Index(['user_id', 'age', 'occupation', 'work_mode', 'device_usage_type',
        'daily_screen_time', 'social_media_hours', 'doomscrolling_duration',
        'app_switch_frequency', 'notification_count', 'smartphone_unlocks',
        'late_night_device_usage', 'focus_sessions', 'deep_work_hours',
        'distraction_frequency', 'task_completion_rate', 'concentration_score',
        'sleep_hours', 'sleep_quality', 'caffeine_intake', 'physical_activity',
        'stress_level', 'workspace_quality', 'meeting_hours',
        'internet_stability', 'remote_work_days', 'motivation_level',
        'mental_fatigue', 'emotional_exhaustion', 'work_satisfaction',
        'mental_state', 'burnout_risk', 'productivity_score',
        'productivity_category'],
       dtype='object'),
 34)

In [4]:
df.shape

(5000000, 34)

In [5]:
df.isna().sum()

user_id                         0
age                             0
occupation                      0
work_mode                       0
device_usage_type               0
daily_screen_time               0
social_media_hours         100000
doomscrolling_duration          0
app_switch_frequency            0
notification_count              0
smartphone_unlocks              0
late_night_device_usage         0
focus_sessions                  0
deep_work_hours            100000
distraction_frequency           0
task_completion_rate            0
concentration_score             0
sleep_hours                100000
sleep_quality                   0
caffeine_intake                 0
physical_activity               0
stress_level                    0
workspace_quality               0
meeting_hours                   0
internet_stability              0
remote_work_days                0
motivation_level           100000
mental_fatigue                  0
emotional_exhaustion            0
work_satisfaction               0
mental_state                    0
burnout_risk                    0
productivity_score              0
productivity_category           0
dtype: int64

In [6]:
((df.isna().sum()/df.shape[0])*100)[df.isna().sum()>0]#percentage

social_media_hours    2.0
deep_work_hours       2.0
sleep_hours           2.0
motivation_level      2.0
dtype: float64

In [7]:
# as the null value percentage is ~ 2% , decided to impute the columns
df["social_media_hours"]=df["social_media_hours"].fillna(df["social_media_hours"].median)
df["deep_work_hours"]=df["deep_work_hours"].fillna(df["deep_work_hours"].median)
df["sleep_hours"]=df["sleep_hours"].fillna(df["sleep_hours"].median)
df["motivation_level"]=df["motivation_level"].fillna(df["motivation_level"].median)

In [8]:
(df.isna().sum())[df.isna().sum()>0]

Series([], dtype: int64)

In [9]:
df.info()#information about dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000000 entries, 0 to 4999999
Data columns (total 34 columns):
 #   Column                   Dtype
---  ------                   -----
 0   user_id                  int64
 1   age                      int64
 2   occupation               object
 3   work_mode                object
 4   device_usage_type        object
 5   daily_screen_time        float64
 6   social_media_hours       object
 7   doomscrolling_duration   float64
 8   app_switch_frequency     int64
 9   notification_count       int64
 10  smartphone_unlocks       int64
 11  late_night_device_usage  int64
 12  focus_sessions           int64
 13  deep_work_hours          object
 14  distraction_frequency    int64
 15  task_completion_rate     int64
 16  concentration_score      int64
 17  sleep_hours              object
 18  sleep_quality            int64
 19  caffeine_intake          int64
 20  physical_activity        float64
 21  stress_level             int64
 22  workspace_quality        int64
 23  meeting_hours            float64
 24  internet_stability       int64
 25  remote_work_days         int64
 26  motivation_level         object
 27  mental_fatigue           int64
 28  emotional_exhaustion     int64
 29  work_satisfaction        int64
 30  mental_state             object
 31  burnout_risk             int64
 32  productivity_score       int64
 33  productivity_category    object
dtypes: float64(4), int64(21), object(9)
memory usage: 1.3+ GB

In [10]:
df_cat=df.select_dtypes(include=["object","category"]).columns.tolist()

In [11]:
for col in df_cat:
  print(col)

occupation
work_mode
device_usage_type
social_media_hours
deep_work_hours
sleep_hours
motivation_level
mental_state
productivity_category

In [12]:
#using label encoder for each cat col and storing the encoder object in a dict
d={}
for col in df_cat:
  le=LabelEncoder()
  df[col]=le.fit_transform(df[col].astype(str))
  d[col]=le
df, d

(         user_id  age  occupation  work_mode  device_usage_type  \
 0              1   56           1          1                  1
 1              2   46           6          0                  2
 2              3   32           5          2                  0
 3              4   25           2          1                  0
 4              5   38           0          0                  2
 ...          ...  ...         ...        ...                ...
 4999995  4999996   45           4          0                  1
 4999996  4999997   26           0          2                  1
 4999997  4999998   58           0          0                  1
 4999998  4999999   54           1          1                  0
 4999999  5000000   27           6          2                  2

          daily_screen_time  social_media_hours  doomscrolling_duration  \
 0                      8.8                  71                     1.2
 1                     10.3                  43                     2.4
 2                      6.5                  67                     1.0
 3                      9.6                  12                     0.1
 4                     13.3                  16                     1.9
 ...                    ...                 ...                     ...
 4999995                8.0                  63                     1.5
 4999996                9.7                  63                     0.8
 4999997               11.0                  60                     1.3
 4999998                8.2                  72                     4.2
 4999999                8.9                  61                     3.1

          app_switch_frequency  notification_count  ...  internet_stability  \
 0                          41                 112  ...                   3
 1                         119                 168  ...                   7
 2                         121                 199  ...                   9
 3                          85                 122  ...                  10
 4                         221                  73  ...                   1
 ...                       ...                 ...  ...                 ...
 4999995                   140                  58  ...                   5
 4999996                    55                 113  ...                   8
 4999997                   106                 103  ...                   9
 4999998                   195                 388  ...                   8
 4999999                   150                 201  ...                   4

          remote_work_days  motivation_level  mental_fatigue  \
 0                       4                 8              10
 1                       6                 5               7
 2                       6                 8               5
 3                       5                 6               4
 4                       1                 4               7
 ...                   ...               ...             ...
 4999995                 1                 4               8
 4999996                 1                 6               9
 4999997                 3                 4               3
 4999998                 4                 7               9
 4999999                 6                 8               6

          emotional_exhaustion  work_satisfaction  mental_state  burnout_risk  \
 0                           4                  8             0            46
 1                           9                  7             0            57
 2                           2                  6             0            29
 3                           5                  3             1            57
 4                           9                  7             3            64
 ...                       ...                ...           ...           ...
 4999995                     9                  3             3            48
 4999996                     7                  8             0            24
 4999997                     1                  8             3            40
 4999998                     8                  8             1           100
 4999999                     8                  4             0            71

          productivity_score  productivity_category
 0                       100                      0
 1                        96                      0
 2                        79                      0
 3                        63                      2
 4                        89                      0
 ...                     ...                    ...
 4999995                  70                      2
 4999996                  99                      0
 4999997                  68                      2
 4999998                  79                      0
 4999999                  64                      2

 [5000000 rows x 34 columns],
 {'occupation': LabelEncoder(),
  'work_mode': LabelEncoder(),
  'device_usage_type': LabelEncoder(),
  'social_media_hours': LabelEncoder(),
  'deep_work_hours': LabelEncoder(),
  'sleep_hours': LabelEncoder(),
  'motivation_level': LabelEncoder(),
  'mental_state': LabelEncoder(),
  'productivity_category': LabelEncoder()})

In [13]:
df.head()

,user_id,age,occupation,work_mode,device_usage_type,daily_screen_time,social_media_hours,doomscrolling_duration,app_switch_frequency,notification_count,...,internet_stability,remote_work_days,motivation_level,mental_fatigue,emotional_exhaustion,work_satisfaction,mental_state,burnout_risk,productivity_score,productivity_category
0,1,56,1,1,1,8.8,71,1.2,41,112,...,3,4,8,10,4,8,0,46,100,0
1,2,46,6,0,2,10.3,43,2.4,119,168,...,7,6,5,7,9,7,0,57,96,0
2,3,32,5,2,0,6.5,67,1.0,121,199,...,9,6,8,5,2,6,0,29,79,0
3,4,25,2,1,0,9.6,12,0.1,85,122,...,10,5,6,4,5,3,1,57,63,2
4,5,38,0,0,2,13.3,16,1.9,221,73,...,1,1,4,7,9,7,3,64,89,0

In [14]:
df.to_csv('processed_digital_burnout_dataset.csv',index=False) #saving